version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: goalcrest_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - DEBUG=1
      - DJANGO_SECRET_KEY=your_secret_key
    depends_on:
      - db
      - redis
    env_file:
      - .env

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: goalcrest_frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true

  db:
    image: postgres:13
    container_name: goalcrest_db
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=your_postgres_user
      - POSTGRES_PASSWORD=your_postgres_password
      - POSTGRES_DB=goalcrest_db
    ports:
      - "5433:5432"

  redis:
    image: redis:alpine
    container_name: goalcrest_redis
    ports:
      - "6378:6379"

  celery:
    build:
      context: .
      dockerfile: Dockerfile.backend  # Same Dockerfile as the Django backend
    container_name: goalcrest_celery
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0 
    command: celery -A goalcrest worker --loglevel=info
    volumes:
      - ./backend:/app
    depends_on:
      - redis
      - db
    env_file:
      - .env

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile.backend  # Same Dockerfile as the Django backend
    container_name: goalcrest_celery_beat
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0 
    command: celery -A goalcrest beat --loglevel=info
    volumes:
      - ./backend:/app
    depends_on:
      - redis
      - db
    env_file:
      - .env

volumes:
  db_data:
