FROM node:18-alpine

WORKDIR /app

COPY frontend/package*.json ./
RUN npm install --save react react-dom react-scripts

# Save node_modules to a separate folder temporarily
RUN cp -r node_modules /node_modules

COPY frontend/ /app
COPY frontend/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

EXPOSE 3000

ENTRYPOINT ["/entrypoint.sh"]
