FROM node:18-slim AS build

WORKDIR /app

# Set the Node.js memory limit (e.g., 2 GB)
ENV NODE_OPTIONS="--max-old-space-size=2048"

# Copy and install dependencies
COPY frontend/package*.json ./
RUN npm install


# Save node_modules to a separate folder temporarily
RUN cp -r node_modules /node_modules

COPY frontend/ /app
COPY frontend/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

EXPOSE 3000

ENTRYPOINT ["/entrypoint.sh"]


