# Generated by Django 5.1.1 on 2024-11-07 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_budget_category_expense_income_recurringexpense_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurringincome',
            name='income',
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.CreateModel(
            name='RecurringTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.expense')),
                ('income', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.income')),
            ],
        ),
        migrations.DeleteModel(
            name='RecurringExpense',
        ),
        migrations.DeleteModel(
            name='RecurringIncome',
        ),
    ]
