name: Pylint Check

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          # Add other dependencies here if needed
          pip install -r backend/requirements.txt  # Adjust path as necessary

      - name: Run Pylint
        run: |
          # Run Pylint and output any issues
          pylint $(git ls-files '*.py') --output-format=colorized --exit-zero
        continue-on-error: true

      - name: Annotate Pylint Warnings
        if: failure()
        uses: sgeisler/pylint-annotations-action@v2
        with:
          pylint-results: pylint_report.txt
          check-name: Pylint Code Quality
